In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,14,Venmo,Fortnightly,NaN,NaN,NaN,NaN,NaN,NaN
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,2,Cash,Fortnightly,NaN,NaN,NaN,NaN,NaN,NaN
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,23,Credit Card,Weekly,NaN,NaN,NaN,NaN,NaN,NaN
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,49,PayPal,Weekly,NaN,NaN,NaN,NaN,NaN,NaN
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,31,PayPal,Annually,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
 18  Unnamed: 18             0 non-null      float64
 19  Unnamed: 19             0 non-null      float64
 20  Unnamed: 20             0 non-null      float64
 21  Unnamed: 21             0 non-null      float64
 22  Unnamed: 22             0 non-null      float64
 23  Unnamed: 23             0 non-null      float64
dtypes: float64(7), int64(4), object(13)
memory usage: 731.4+ KB

In [7]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,1950.500000,44.068462,59.764359,3.750065,25.351538,NaN,NaN,NaN,NaN,NaN,NaN
std,1125.977353,15.207589,23.685392,0.716983,14.447125,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,18.000000,20.000000,2.500000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,975.750000,31.000000,39.000000,3.100000,13.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,1950.500000,44.000000,60.000000,3.800000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,3900.000000,70.000000,100.000000,5.000000,50.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:

df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,...,3900,3900.000000,3900,3900,0.0,0.0,0.0,0.0,0.0,0.0
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,...,2,NaN,6,7,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,...,No,NaN,PayPal,Every 3 Months,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,...,2223,NaN,677,584,NaN,NaN,NaN,NaN,NaN,NaN
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,...,NaN,25.351538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,...,NaN,14.447125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,...,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,...,NaN,13.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,...,NaN,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,...,NaN,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,...,NaN,50.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)        0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating               37
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
Unnamed: 18               3900
Unnamed: 19               3900
Unnamed: 20               3900
Unnamed: 21               3900
Unnamed: 22               3900
Unnamed: 23               3900
dtype: int64

In [13]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [15]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (USD)        0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
Unnamed: 18               3900
Unnamed: 19               3900
Unnamed: 20               3900
Unnamed: 21               3900
Unnamed: 22               3900
Unnamed: 23               3900
dtype: int64

In [17]:
df.columns = df.columns.str.lower()

In [19]:
df.columns

Index(['customer id', 'age', 'gender', 'item purchased', 'category',
       'purchase amount (usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchases',
       'payment method', 'frequency of purchases', 'unnamed: 18',
       'unnamed: 19', 'unnamed: 20', 'unnamed: 21', 'unnamed: 22',
       'unnamed: 23'],
      dtype='object')

In [21]:
df.columns = df.columns.str.replace(' ','_')

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18',
       'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
       'unnamed:_23'],
      dtype='object')

In [25]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [27]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18',
       'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
       'unnamed:_23'],
      dtype='object')

In [29]:
df =df.rename(columns={'color':'colour'})

In [31]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18',
       'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
       'unnamed:_23'],
      dtype='object')

In [33]:
#create a columns age_group
labels = ['Young Adult', 'Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [35]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [37]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18',
       'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
       'unnamed:_23', 'age_group'],
      dtype='object')

In [39]:
#Create columns purchase_frequency_days

frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Annnually': 365,
    'Every 3 Months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [41]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18',
       'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
       'unnamed:_23', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [43]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                      NaN               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                      NaN               Annually
9                     90.0              Quarterly

In [45]:
frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Quarterly': 90,
    'Annually': 365
}

In [47]:
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [49]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [51]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [53]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18',
       'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
       'unnamed:_23', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [55]:
df[['customer_id','age']].head(10)

   customer_id  age
0            1   55
1            2   19
2            3   50
3            4   21
4            5   45
5            6   46
6            7   63
7            8   27
8            9   26
9           10   57

In [57]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [59]:
(df['customer_id'] ==df ['age']).all()

False

In [61]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\vaibhav\appdata\roaming\python\python312\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [62]:
from sqlalchemy import create_engine
#step 1:connect to postgreSQL
#Replace placeholders with your actual details
username = 'postgres'
password = 1234
host = 'localhost'
port = 5432
database = 'customer_behavior'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2 :Load dataframe into postgreSQL
table_name = 'customer'
df.to_sql(table_name, engine, if_exists='replace',index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.